### ISSUE TITLE
无文件名打开vi时出错

### ISSUE THREAD

**Issue by dongly** [RT-Thread-packages/vi#23]
* 问题: 无文件名打开vi时,出错
```shell
msh />vi

filename != NULL) assertion failed at function:dfs_normalize_path, line number:382
```
* 环境
  * vi lastest
  * rt-thread master https://github.com/RT-Thread/rt-thread/commit/49ccbdb85199a6aa33b559856e6ed9e4328e62b9
  * GCC  :arm-none-eabi-gcc (GNU Arm Embedded Toolchain 10-2020-q4-major) 10.2.1 20201103 (release)
  * 测试BSP stm32f407-atk-explorer

* 另编译有警告,strncasecmp未实现,加入"#include strings.h"解决

**Comment by mysterywolf** [comment]
感谢反馈 等修好了 通知你，我在忙其他事情，三天内给你回复

**Comment by mysterywolf** [comment]
你好问题已经修复了，请再拉取最新的软件包试一下，如果是用gitee镜像源的话需要等到明天才行。

**Comment by dongly** [comment]
谢谢

**Comment by dongly** [comment]
无文件名时,无任何提示.

**Comment by mysterywolf** [comment]
我又改了一下 你试试

**Comment by mysterywolf** [comment]
得明天，我更改了一下软件包的Kconfig配置，得明天凌晨才能同步中国大陆镜像源（gitee）
